debug: true
url: "ldap://127.0.0.1:38938"
baseDn: "dc=demo,dc=lab"
ldapUsername: "ldapuser"
ldapPassword: "ldapPASSW0RD"
ldapFilter: "(objectClass=person)"
caCertPath: "./ca_cert.pem"
caKeyPath: "./ca_key.pem"
caPassword: "CApassword"
certValidityDays: 30
certKeySize: 2048